### PR TITLE
fix inefficient usage of batch_save

### PR DESCRIPTION
**Pull request by zszia**

### CODE REVIEW

**Comment by zszia** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by zszia** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Comment by arys-splunk** [comment]
Tested it locally, works fine, can I ask you to change the commit message to use https://www.conventionalcommits.org/en/v1.0.0/. `refactor` prefix should work fine.

**Comment by zszia** [comment]
Changed the commit description

**Review by arys-splunk — APPROVED** [review]
I do not know why the CI is not running, but this change was tested locally by me and it looks good to me.

Thank you for the contribution.

**Pull request merged**
