### PR TITLE
fix splunk config parsing in Python 3.13

### PR DESCRIPTION
**Pull request by echipachenko**
I have read the Code of Conduct and I hereby accept the Terms

I have read the CLA Document and I hereby accept the CLA

### CODE REVIEW

**Comment by hetangmodi-crest** [comment]
Hi @echipachenko, are you using `solnlib` outside Splunk environment?

**Comment by echipachenko** [comment]
recheck

**Comment by echipachenko** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Comment by echipachenko** [comment]
I have read the CLA Document and I hereby accept the CLA

**Comment by echipachenko** [comment]
recheck

**Review by sgoral-splunk — APPROVED** [review]
lgtm

**Pull request closed without merging**
