### PR TITLE
Fix lazy initialization of the checkpointer

### PR DESCRIPTION
**Pull request by zszia**

### CODE REVIEW

**Comment by arys-splunk** [comment]
I tested it locally, reproduced the issue and your fix is working.

**Comment by arys-splunk** [comment]
Can I ask you to use https://www.conventionalcommits.org/en/v1.0.0/ in your commit message so we can release the fix after I merge this PR?

**Comment by zszia** [comment]
Changed the commit description

**Review by arys-splunk — APPROVED** [review]
`snyk` and `semgrep` are failing due to some permission issues, but they should be fine, as this PR does not change anything that can break them.

I tested it locally, reproduced a bug and this fix is working.

Thank you for the contribution.

**Pull request merged**
